# Generated by Django 5.1.1 on 2024-10-22 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='Biblioteca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_biblioteca', to='prueba.biblioteca'),
        ),
    ]
